apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: execute-techacademy-db
  namespace: execute-techacademy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: execute-techacademy-db
    creationPolicy: Owner
    template:
      data:
        DB_HOST: "<RDS_ENDPOINT>"
        DB_NAME: "<RDS_DB_NAME>"
        DB_USER: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: "<RDS_SECRET_ARN>"